import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const base = join(dirname(fileURLToPath(import.meta.url)), '..');
const source = await readFile(join(base, 'shared/install.mjs'), 'utf8');
const encoded = Buffer.from(source).toString('base64');
const run = `try{const m=await import('data:text/javascript;base64,${encoded}');await m.install(await m.release(process.argv[1],process.argv[2]));}catch(e){console.error(e.message);process.exitCode=1;}`;
const installer = `#!/bin/bash\nset -euo pipefail\ncd /mnt/server\nexport PATH="/usr/local/bin:$PATH"\nnode --input-type=module -e "${run}" "\${SQUADXO_REPO:-vohk/SquadXO}" "\${SQUADXO_TAG:-latest}"\n`;
const egg = {
  _comment:
    'Generated by deployment/shared/generate.mjs. Import into Pterodactyl 1.x, Pelican or WISP.',
  meta: { version: 'PTDL_v2', update_url: null },
  exported_at: '2026-10-09T00:00:00+00:00',
  name: 'SquadXO',
  author: 'squadxo@users.noreply.github.com',
  description:
    'Public compiled SquadXO releases. Configure config.json yourself. Updates retain all user files and previous application versions.',
  features: null,
  docker_images: { 'Node.js 24': 'ghcr.io/ptero-eggs/yolks:nodejs_24' },
  file_denylist: [],
  startup: 'node --unhandled-rejections=warn index.js --config config.json',
  config: {
    files: '{}',
    startup: JSON.stringify({ done: 'SquadXO runtime started.' }),
    logs: '{}',
    stop: '^C'
  },
  scripts: {
    installation: { script: installer, container: 'node:24-trixie-slim', entrypoint: 'bash' }
  },
  variables: [
    {
      name: 'Public GitHub repository',
      description: 'Public repository publishing SquadXO deployment archives, not source archives.',
      env_variable: 'SQUADXO_REPO',
      default_value: 'vohk/SquadXO',
      user_viewable: true,
      user_editable: true,
      rules: 'required|string|regex:#^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$#',
      field_type: 'text'
    },
    {
      name: 'Release tag',
      description: 'latest or an exact v-prefixed public release tag.',
      env_variable: 'SQUADXO_TAG',
      default_value: 'latest',
      user_viewable: true,
      user_editable: true,
      rules: 'required|string|regex:/^(latest|v[0-9A-Za-z._-]{1,64})$/',
      field_type: 'text'
    }
  ]
};
const wisp = installer.replace('cd /mnt/server', 'cd /home/container');
const ampUpdates = [
  {
    UpdateStageName: 'Verified SquadXO deployment',
    UpdateSourcePlatform: 'Linux',
    UpdateSource: 'Executable',
    UpdateSourceData: '{{NodeExecutable}}',
    UpdateSourceArgs: `--input-type=module -e "${run}" "{{Repository}}" "{{ReleaseTag}}"`,
    SkipOnFailure: false
  }
];
const outputs = new Map([
  ['pterodactyl/egg-squadxo.json', `${JSON.stringify(egg, null, 2)}\n`],
  ['wisp/update.sh', wisp],
  ['amp/squadxoupdates.json', `${JSON.stringify(ampUpdates, null, 2)}\n`]
]);
for (const [path, contents] of outputs) {
  if (process.argv.includes('--check')) {
    if ((await readFile(join(base, path), 'utf8')) !== contents)
      throw new Error(`Regenerate deployment/${path}`);
  } else await writeFile(join(base, path), contents);
}
